// packages/team8-analytics/src/components/Sidebar.tsx
'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { BarChart3, TrendingUp, Users, Package, DollarSign, FileText, Settings } from 'lucide-react';

const menuItems = [
  { path: '/', icon: BarChart3, label: 'Dashboard' },
  { path: '/sales', icon: DollarSign, label: 'Sales Analytics' },
  { path: '/inventory', icon: Package, label: 'Inventory' },
  { path: '/customers', icon: Users, label: 'Customers' },
  { path: '/forecasting', icon: TrendingUp, label: 'Forecasting' },
  { path: '/reports', icon: FileText, label: 'Custom Reports' },
];

export default function Sidebar() {
  const pathname = usePathname();

  return (
    <div className="w-64 bg-gradient-to-b from-indigo-900 to-indigo-800 text-white flex flex-col">
      <div className="p-6 border-b border-indigo-700">
        <h1 className="text-2xl font-bold">📊 Analytics</h1>
        <p className="text-sm text-indigo-300 mt-1">Business Intelligence</p>
      </div>

      <nav className="flex-1 p-4 space-y-2">
        {menuItems.map((item) => {
          const Icon = item.icon;
          const isActive = pathname === item.path;
          
          return (
            <Link
              key={item.path}
              href={item.path}
              className={`flex items-center space-x-3 px-4 py-3 rounded-lg transition-colors ${
                isActive
                  ? 'bg-indigo-700 text-white'
                  : 'text-indigo-200 hover:bg-indigo-800 hover:text-white'
              }`}
            >
              <Icon className="w-5 h-5" />
              <span>{item.label}</span>
            </Link>
          );
        })}
      </nav>

      <div className="p-4 border-t border-indigo-700">
        <div className="flex items-center space-x-3 px-4 py-3">
          <div className="w-8 h-8 rounded-full bg-indigo-600 flex items-center justify-center">
            <Settings className="w-4 h-4" />
          </div>
          <div>
            <div className="font-medium">Admin User</div>
            <div className="text-xs text-indigo-300">BI Analyst</div>
          </div>
        </div>
      </div>
    </div>
  );
}

// packages/team7-customer-service/src/components/Sidebar.svelte
<script lang="ts">
  import { link } from 'svelte-routing'
  
  export let open = true

  const menuItems = [
    { path: '/', icon: '📊', label: 'Dashboard' },
    { path: '/tickets', icon: '🎫', label: 'Tickets' },
    { path: '/customers', icon: '👥', label: 'Customers' },
    { path: '/chat', icon: '💬', label: 'Live Chat' },
    { path: '/knowledge-base', icon: '📚', label: 'Knowledge Base' },
    { path: '/reports', icon: '📈', label: 'Reports' }
  ]

  let activeItem = '/'
  
  function setActive(path: string) {
    activeItem = path
  }
</script>

<aside class="w-64 bg-gradient-to-b from-blue-900 to-blue-800 text-white flex-shrink-0 shadow-xl">
  <div class="p-6">
    <div class="flex items-center gap-3 mb-8">
      <div class="w-12 h-12 bg-white rounded-lg flex items-center justify-center text-2xl">
        🏢
      </div>
      <div>
        <h1 class="text-xl font-bold">Gajah Nusa</h1>
        <p class="text-sm text-blue-200">Customer Service</p>
      </div>
    </div>

    <nav class="space-y-2">
      {#each menuItems as item}
        <a
          href={item.path}
          use:link
          on:click={() => setActive(item.path)}
          class="flex items-center gap-3 px-4 py-3 rounded-lg transition-all hover:bg-blue-700 {activeItem === item.path ? 'bg-blue-700 font-semibold' : ''}"
        >
          <span class="text-2xl">{item.icon}</span>
          <span>{item.label}</span>
        </a>
      {/each}
    </nav>
  </div>

  <div class="absolute bottom-0 left-0 right-0 p-6 border-t border-blue-700">
    <div class="flex items-center gap-3">
      <div class="w-10 h-10 bg-blue-600 rounded-full flex items-center justify-center font-bold">
        CS
      </div>
      <div class="flex-1">
        <div class="font-semibold">CS Agent</div>
        <div class="text-sm text-blue-200">agent@gajahnusa.com</div>
      </div>
    </div>
  </div>
</aside>
